import 'package:ledger_mobile/data/models/currency_model.dart';

final currencyInserts =
    """
  INSERT INTO ${CurrencyModel.tableName} (${CurrencyModel.fieldCurrencyId}, ${CurrencyModel.fieldName}, ${CurrencyModel.fieldCode}, ${CurrencyModel.fieldSymbol}, ${CurrencyModel.fieldFlagIcon}) VALUES 
  ('USD', 'United States Dollar', 'USD', '\$', '🇺🇸'),
  ('EUR', 'Euro', 'EUR', '€', '🇪🇺'),
  ('JPY', 'Japanese Yen', 'JPY', '¥', '🇯🇵'),
  ('GBP', 'British Pound Sterling', 'GBP', '£', '🇬🇧'),
  ('AUD', 'Australian Dollar', 'AUD', 'A\$', '🇦🇺'),
  ('CAD', 'Canadian Dollar', 'CAD', 'C\$', '🇨🇦'),
  ('CHF', 'Swiss Franc', 'CHF', 'CHF', '🇨🇭'),
  ('CNY', 'Chinese Yuan', 'CNY', '¥', '🇨🇳'),
  ('SEK', 'Swedish Krona', 'SEK', 'kr', '🇸🇪'),
  ('NZD', 'New Zealand Dollar', 'NZD', 'NZ\$', '🇳🇿'),
  ('MXN', 'Mexican Peso', 'MXN', '\$', '🇲🇽'),
  ('SGD', 'Singapore Dollar', 'SGD', 'S\$', '🇸🇬'),
  ('HKD', 'Hong Kong Dollar', 'HKD', 'HK\$', '🇭🇰'),
  ('NOK', 'Norwegian Krone', 'NOK', 'kr', '🇳🇴'),
  ('KRW', 'South Korean Won', 'KRW', '₩', '🇰🇷'),
  ('TRY', 'Turkish Lira', 'TRY', '₺', '🇹🇷'),
  ('INR', 'Indian Rupee', 'INR', '₹', '🇮🇳'),
  ('RUB', 'Russian Ruble', 'RUB', '₽', '🇷🇺'),
  ('BRL', 'Brazilian Real', 'BRL', 'R\$', '🇧🇷'),
  ('ZAR', 'South African Rand', 'ZAR', 'R', '🇿🇦'),
  ('DKK', 'Danish Krone', 'DKK', 'kr', '🇩🇰'),
  ('PLN', 'Polish Zloty', 'PLN', 'zł', '🇵🇱'),
  ('TWD', 'New Taiwan Dollar', 'TWD', 'NT\$', '🇹🇼'),
  ('THB', 'Thai Baht', 'THB', '฿', '🇹🇭'),
  ('IDR', 'Indonesian Rupiah', 'IDR', 'Rp', '🇮🇩'),
  ('HUF', 'Hungarian Forint', 'HUF', 'Ft', '🇭🇺'),
  ('CZK', 'Czech Koruna', 'CZK', 'Kč', '🇨🇿'),
  ('ILS', 'Israeli New Shekel', 'ILS', '₪', '🇮🇱'),
  ('CLP', 'Chilean Peso', 'CLP', '\$', '🇨🇱'),
  ('PHP', 'Philippine Peso', 'PHP', '₱', '🇵🇭'),
  ('AED', 'UAE Dirham', 'AED', 'د.إ', '🇦🇪'),
  ('COP', 'Colombian Peso', 'COP', '\$', '🇨🇴'),
  ('SAR', 'Saudi Riyal', 'SAR', '﷼', '🇸🇦'),
  ('MYR', 'Malaysian Ringgit', 'MYR', 'RM', '🇲🇾'),
  ('RON', 'Romanian Leu', 'RON', 'lei', '🇷🇴'),
  ('VND', 'Vietnamese Dong', 'VND', '₫', '🇻🇳'),
  ('ARS', 'Argentine Peso', 'ARS', '\$', '🇦🇷'),
  ('EGP', 'Egyptian Pound', 'EGP', 'E£', '🇪🇬'),
  ('PKR', 'Pakistani Rupee', 'PKR', '₨', '🇵🇰'),
  ('IQD', 'Iraqi Dinar', 'IQD', 'ع.د', '🇮🇶'),
  ('KWD', 'Kuwaiti Dinar', 'KWD', 'د.ك', '🇰🇼'),
  ('QAR', 'Qatari Rial', 'QAR', 'ر.ق', '🇶🇦'),
  ('PEN', 'Peruvian Sol', 'PEN', 'S/.', '🇵🇪'),
  ('UAH', 'Ukrainian Hryvnia', 'UAH', '₴', '🇺🇦'),
  ('KZT', 'Kazakhstani Tenge', 'KZT', '₸', '🇰🇿'),
  ('NGN', 'Nigerian Naira', 'NGN', '₦', '🇳🇬'),
  ('BDT', 'Bangladeshi Taka', 'BDT', '৳', '🇧🇩'),
  ('MAD', 'Moroccan Dirham', 'MAD', 'د.م.', '🇲🇦'),
  ('TND', 'Tunisian Dinar', 'TND', 'د.ت', '🇹🇳'),
  ('DZD', 'Algerian Dinar', 'DZD', 'د.ج', '🇩🇿'),
  ('GHS', 'Ghanaian Cedi', 'GHS', '₵', '🇬🇭'),
  ('KES', 'Kenyan Shilling', 'KES', 'KSh', '🇰🇪'),
  ('UGX', 'Ugandan Shilling', 'UGX', 'USh', '🇺🇬'),
  ('TZS', 'Tanzanian Shilling', 'TZS', 'TSh', '🇹🇿'),
  ('ETB', 'Ethiopian Birr', 'ETB', 'Br', '🇪🇹'),
  ('LKR', 'Sri Lankan Rupee', 'LKR', 'Rs', '🇱🇰'),
  ('NPR', 'Nepalese Rupee', 'NPR', '₨', '🇳🇵'),
  ('MMK', 'Myanmar Kyat', 'MMK', 'K', '🇲🇲'),
  ('KHR', 'Cambodian Riel', 'KHR', '៛', '🇰🇭'),
  ('LAK', 'Lao Kip', 'LAK', '₭', '🇱🇦'),
  ('JOD', 'Jordanian Dinar', 'JOD', 'د.ا', '🇯🇴'),
  ('LBP', 'Lebanese Pound', 'LBP', 'L£', '🇱🇧'),
  ('OMR', 'Omani Rial', 'OMR', 'ر.ع.', '🇴🇲'),
  ('BHD', 'Bahraini Dinar', 'BHD', '.د.ب', '🇧🇭'),
  ('ISK', 'Icelandic Króna', 'ISK', 'kr', '🇮🇸'),
  ('HRK', 'Croatian Kuna', 'HRK', 'kn', '🇭🇷'),
  ('BGN', 'Bulgarian Lev', 'BGN', 'лв', '🇧🇬'),
  ('GEL', 'Georgian Lari', 'GEL', '₾', '🇬🇪'),
  ('AMD', 'Armenian Dram', 'AMD', '֏', '🇦🇲'),
  ('AZN', 'Azerbaijani Manat', 'AZN', '₼', '🇦🇿'),
  ('BYN', 'Belarusian Ruble', 'BYN', 'Br', '🇧🇾'),
  ('MDL', 'Moldovan Leu', 'MDL', 'L', '🇲🇩'),
  ('MNT', 'Mongolian Tögrög', 'MNT', '₮', '🇲🇳'),
  ('UZS', 'Uzbekistani Som', 'UZS', 'so\'m', '🇺🇿'),
  ('TJS', 'Tajikistani Somoni', 'TJS', 'SM', '🇹🇯'),
  ('TMT', 'Turkmenistani Manat', 'TMT', 'm', '🇹🇲'),
  ('AFN', 'Afghan Afghani', 'AFN', '؋', '🇦🇫'),
  ('ALL', 'Albanian Lek', 'ALL', 'L', '🇦🇱'),
  ('AOA', 'Angolan Kwanza', 'AOA', 'Kz', '🇦🇴'),
  ('AWG', 'Aruban Florin', 'AWG', 'ƒ', '🇦🇼'),
  ('BAM', 'Bosnia and Herzegovina Convertible Mark', 'BAM', 'KM', '🇧🇦'),
  ('BBD', 'Barbadian Dollar', 'BBD', '\$', '🇧🇧'),
  ('BIF', 'Burundian Franc', 'BIF', 'Fr', '🇧🇮'),
  ('BMD', 'Bermudian Dollar', 'BMD', '\$', '🇧🇲'),
  ('BND', 'Brunei Dollar', 'BND', '\$', '🇧🇳'),
  ('BOB', 'Bolivian Boliviano', 'BOB', 'Bs.', '🇧🇴'),
  ('BSD', 'Bahamian Dollar', 'BSD', '\$', '🇧🇸'),
  ('BTN', 'Bhutanese Ngultrum', 'BTN', 'Nu.', '🇧🇹'),
  ('BWP', 'Botswana Pula', 'BWP', 'P', '🇧🇼'),
  ('BZD', 'Belize Dollar', 'BZD', '\$', '🇧🇿'),
  ('CDF', 'Congolese Franc', 'CDF', 'Fr', '🇨🇩'),
  ('CRC', 'Costa Rican Colón', 'CRC', '₡', '🇨🇷'),
  ('CUP', 'Cuban Peso', 'CUP', '\$', '🇨🇺'),
  ('CVE', 'Cape Verdean Escudo', 'CVE', 'Esc', '🇨🇻'),
  ('DJF', 'Djiboutian Franc', 'DJF', 'Fr', '🇩🇯'),
  ('DOP', 'Dominican Peso', 'DOP', '\$', '🇩🇴'),
  ('ERN', 'Eritrean Nakfa', 'ERN', 'Nfk', '🇪🇷'),
  ('FJD', 'Fijian Dollar', 'FJD', '\$', '🇫🇯'),
  ('FKP', 'Falkland Islands Pound', 'FKP', '£', '🇫🇰'),
  ('GIP', 'Gibraltar Pound', 'GIP', '£', '🇬🇮'),
  ('GMD', 'Gambian Dalasi', 'GMD', 'D', '🇬🇲'),
  ('GNF', 'Guinean Franc', 'GNF', 'Fr', '🇬🇳'),
  ('GTQ', 'Guatemalan Quetzal', 'GTQ', 'Q', '🇬🇹'),
  ('GYD', 'Guyanese Dollar', 'GYD', '\$', '🇬🇾'),
  ('HNL', 'Honduran Lempira', 'HNL', 'L', '🇭🇳'),
  ('HTG', 'Haitian Gourde', 'HTG', 'G', '🇭🇹'),
  ('JMD', 'Jamaican Dollar', 'JMD', '\$', '🇯🇲'),
  ('KGS', 'Kyrgyzstani Som', 'KGS', 'с', '🇰🇬'),
  ('KMF', 'Comorian Franc', 'KMF', 'Fr', '🇰🇲'),
  ('KYD', 'Cayman Islands Dollar', 'KYD', '\$', '🇰🇾'),
  ('LSL', 'Lesotho Loti', 'LSL', 'L', '🇱🇸'),
  ('LYD', 'Libyan Dinar', 'LYD', 'ل.د', '🇱🇾'),
  ('MGA', 'Malagasy Ariary', 'MGA', 'Ar', '🇲🇬'),
  ('MKD', 'Macedonian Denar', 'MKD', 'ден', '🇲🇰'),
  ('MOP', 'Macanese Pataca', 'MOP', 'P', '🇲🇴'),
  ('MRU', 'Mauritanian Ouguiya', 'MRU', 'UM', '🇲🇷'),
  ('MUR', 'Mauritian Rupee', 'MUR', '₨', '🇲🇺'),
  ('MVR', 'Maldivian Rufiyaa', 'MVR', 'Rf', '🇲🇻'),
  ('MWK', 'Malawian Kwacha', 'MWK', 'MK', '🇲🇼'),
  ('MZN', 'Mozambican Metical', 'MZN', 'MT', '🇲🇿'),
  ('NAD', 'Namibian Dollar', 'NAD', '\$', '🇳🇦'),
  ('NIO', 'Nicaraguan Córdoba', 'NIO', 'C\$', '🇳🇮'),
  ('PAB', 'Panamanian Balboa', 'PAB', 'B/.', '🇵🇦'),
  ('PGK', 'Papua New Guinean Kina', 'PGK', 'K', '🇵🇬'),
  ('PYG', 'Paraguayan Guaraní', 'PYG', '₲', '🇵🇾'),
  ('RWF', 'Rwandan Franc', 'RWF', 'Fr', '🇷🇼'),
  ('SBD', 'Solomon Islands Dollar', 'SBD', '\$', '🇸🇧'),
  ('SCR', 'Seychellois Rupee', 'SCR', '₨', '🇸🇨'),
  ('SDG', 'Sudanese Pound', 'SDG', '£', '🇸🇩'),
  ('SHP', 'Saint Helena Pound', 'SHP', '£', '🇸🇭'),
  ('SLL', 'Sierra Leonean Leone', 'SLL', 'Le', '🇸🇱'),
  ('SOS', 'Somali Shilling', 'SOS', 'Sh', '🇸🇴'),
  ('SRD', 'Surinamese Dollar', 'SRD', '\$', '🇸🇷'),
  ('SSP', 'South Sudanese Pound', 'SSP', '£', '🇸🇸'),
  ('STN', 'São Tomé and Príncipe Dobra', 'STN', 'Db', '🇸🇹'),
  ('SVC', 'Salvadoran Colón', 'SVC', '₡', '🇸🇻'),
  ('SYP', 'Syrian Pound', 'SYP', '£', '🇸🇾'),
  ('SZL', 'Eswatini Lilangeni', 'SZL', 'L', '🇸🇿'),
  ('TOP', 'Tongan Pa\'anga', 'TOP', 'T\$', '🇹🇴'),
  ('TTD', 'Trinidad and Tobago Dollar', 'TTD', '\$', 'TT\$', '🇹🇹'),
  ('UYU', 'Uruguayan Peso', 'UYU', '\$', '🇺🇾'),
  ('VUV', 'Vanuatu Vatu', 'VUV', 'Vt', '🇻🇺'),
  ('WST', 'Samoan Tala', 'WST', 'T', '🇼🇸'),
  ('XAF', 'Central African CFA Franc', 'XAF', 'Fr', '🇨🇲'),
  ('XCD', 'East Caribbean Dollar', 'XCD', '\$', '🇦🇮'),
  ('XOF', 'West African CFA Franc', 'XOF', 'Fr', '🇧🇯'),
  ('XPF', 'CFP Franc', 'XPF', 'Fr', '🇵🇫'),
  ('YER', 'Yemeni Rial', 'YER', '﷼', '🇾🇪'),
  ('ZMW', 'Zambian Kwacha', 'ZMW', 'ZK', '🇿🇲'),
  ('ZWL', 'Zimbabwean Dollar', 'ZWL', '\$', '🇿🇼');
""";
